#!/usr/bin/env python3

from datetime import datetime, timedelta, timezone
from contacts import Contacts

contacts = Contacts()

non_members = contacts.levels['New Applicant']
# Non-members that have not logged in within the past 60 days are past the
# threshold for archiving.
archive_threshold = timedelta(60)
now = datetime.now(timezone.utc)

for contact_id in non_members:
    contact = non_members[contact_id]

    if contact.last_login < now - archive_threshold:
        print(contact.name)
