#!/usr/bin/env python3

from session import Session
from config import Config

config = Config()
session = Session(config)
members = {}

for contact in session.get('contacts')['Contacts']:
    if 'MembershipLevel' not in contact:
        continue

    level = contact['MembershipLevel']['Name']
    email = contact['Email']

    if level not in members:
        members[level] = {email}
    else:
        members[level].add(email)

from pprint import pprint
pprint(members)
