#!/usr/bin/env python3

from argparse import ArgumentParser
from configparser import ConfigParser
from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

CLIENT_ID = 'APIKEY'

# Parse command-line arguments.
parser = ArgumentParser()
parser.add_argument('-c', '--config', required = True, help = 'Path to configuration file.')
args = parser.parse_args()

# Read configuration file.
config = ConfigParser()
config.read(args.config)

client = BackendApplicationClient(client_id = CLIENT_ID)

with OAuth2Session(client = client, scope = 'account_view') as session:
    token = session.fetch_token(config['server']['auth'], client_id = CLIENT_ID, client_secret = config['client']['secret'], scope = 'auto')

    response = session.get(config['server']['api'] + '/v2.1/accounts')

    if response.ok:
        from pprint import pprint
        pprint(response.json())
    else:
        print(response.status_code, response.reason)
        print(token)
