#!/usr/bin/env python3

from argparse import ArgumentParser
from configparser import ConfigParser
from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

CLIENT_ID = 'APIKEY'

# Parse command-line arguments.
parser = ArgumentParser()
parser.add_argument('-c', '--config', required = True, help = 'Path to configuration file.')
args = parser.parse_args()

# Read configuration file.
config = ConfigParser()
config.read(args.config)

client = BackendApplicationClient(client_id = CLIENT_ID)
oauth = OAuth2Session(client = client)
token = oauth.fetch_token(config['server']['auth'], client_id = CLIENT_ID, client_secret = config['client']['secret'])
