#!/usr/bin/env python3

from archive import archive
from args import args
import config
from contacts import Contacts
from datetime import datetime, timezone
from describe import describe
import sys
from tzlocal import get_localzone

now = datetime.now(timezone.utc)
contacts = Contacts()

if 1 < len(args.operations):
    print(f'\n{now.astimezone(get_localzone()):%c}')

operations = {
        'archive': lambda x: archive(contacts, now),
        'describe': lambda x: describe(contacts, x),
        }

for op in args.operations:
    if op[0] not in operations:
        print(f'Error: {op[0]} is not a valid operation', file = sys.stderr)
        continue

    print()
    operations[op[0]](op[1:])
